@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

participant System as route

-> route: POST /robottypes
activate route
  <-- route: 201 CREATED
  deactivate
@enduml