@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

participant System as route

-> route: GET /floors/withConnections/:id
activate route
  <-- route: 200 OK
  deactivate
@enduml