@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false


actor User as user
participant UI 
participant MasterDataDevices 

user -> UI : 1. List Buildings sending an interval of number of floors
activate UI

UI -> MasterDataDevices : 1.1 GET buildings/min/max
activate MasterDataDevices

MasterDataDevices -> MasterDataDevices : validate input

MasterDataDevices --> UI : 1.3 buildings(JSON)
deactivate MasterDataDevices

UI --> user : 1.4 List of Buildings

deactivate UI
@enduml