@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

participant CampusManager as CP
participant System as sys

activate CP
 CP -> sys: getBuildingConnections
  activate sys
  sys --> CP: buildingConnections list
  deactivate sys
@enduml