@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

participant CampusManager as CP
participant UI as UI
participant MasterDataDevices as MDD

activate CP
 CP -> UI: getBuildingConnections
  activate UI
   UI -> MDD: GET /buildings
   activate MDD
    MDD --> UI: buildings(json)
   deactivate MDD
   UI --> CP: displays buildings and asks to choose two
  deactivate UI
 CP -> UI: chooses both buildings
  activate UI
   UI -> MDD: GET /buildingConnections/buildingId1/buildingId2
   activate MDD
    MDD --> UI: buildingconnections(json)
   deactivate MDD
   UI -> MDD: GET /floors/building1
   activate MDD
    MDD --> UI: floors1(json)
   deactivate MDD
   UI -> MDD: GET /floors/building2
   activate MDD
    MDD --> UI: floors2(json)
   deactivate MDD
   UI --> CP: lists building connections between the two buildings
   deactivate UI
@enduml