@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

participant Admin as AD
participant UI as UI
participant UserManagement as UM


activate AD
 AD -> UI: accept-refuser-user-registration
  activate UI
   UI -> UM: GET /auth/get/waiting/decision/users
   activate UM
    UM --> UI: Users(json)
   deactivate UM
   UI -> UM: PATCH /users/{decision}-registration/:id
   activate UM
    UM --> UI: User(json)
   deactivate UM
  UI --> AD: User approved/rejected
  deactivate UI
@enduml