@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

participant Admin as AD
participant UI as UI
participant UserManagement as UM


activate AD
 AD -> UI: Check user's own data
  activate UI
   UI -> UM: GET /me
   activate UM
    UM --> UI: User(json)
   deactivate UM
   
  UI --> AD: User Data
  deactivate UI
@enduml