@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false


actor User as user
participant UI
participant MasterDataDevices

user -> UI : 1. List robots
activate UI

UI -> MasterDataDevices : 1.1 GET robots
activate MasterDataDevices

MasterDataDevices --> UI : 1.2 robots(JSON)
deactivate MasterDataDevices

UI --> user : 1.3 Lists robots

deactivate UI
@enduml